options:
  test:
    type: boolean
    default: False
    description: >
      Generate test certificates ( without a request limit ) instead of
      real trusted certificates.
  http-port:
    type: int
    default: 80
    description: The HTTP listening port
  https-port:
    type: int
    default: 443
    description: The HTTPS listening port
